/* PSEUDOCODE ATTEMPT

CREATE FOUR FUNCTIONS (addNums, subtractNums, multiplyNums, divideNums), 
    FOR THE FOUR MATHEMATICAL OPERATORS, 
    THAT TAKE TWO VALUES (firstNum & secondNum)
    AND COMPUTE ANSWER BASED ON OPERATOR
WHILE NUMBER BUTTON IS NOT CLICKED, 
    DO NOTHING
ONCE NUMBER BUTTON IS CLICKED, 
    DISPLAY THAT NUMBER 
    AND SAVE IT AS A VARIABLE
IF MULTIPLE NUMBER BUTTONS ARE CLICKED IN SUCCESSION,
    UPDATE DISPLAY ACCORDINGLY
    AND APPEND TO THE AFORMENTIONED VARIABLE
ONCE OPERATOR IS CLICKED, 
    SAVE OPERATOR TYPE IN VARIABLE,
    AND CREATE NEW VARIABLE TO HOLD SECOND NUMBER
ONCE EQUALS IS CLICKED, 
    CALL A FUNCTION DEPENDING ON OPERATOR TO COMPUTE ANSWER
    MAKE THE FUNCTION RETURN THE ANSWER
    AND UPDATE THE ANSWER ON THE DISPLAY
IF AN OPERATOR OR THE EQUALS IS CLICKED MULTIPLE TIMES IN SUCCESSION,
    REJECT ALL OPERATOR INPUTS AFTER THE FIRST
IF SCREEN BECOMES FULL BUT THE USER CONTINUES CLICKING NUMBERS, 
    DO NOT DISPLAY MORE ON SCREEN
    BUT UPDATE VARIABLES ACCORDINGLY
IF ANY NUMBER, WHETHER INPUT OR OUTPUT, IS 
    LARGER THAN 9007199254740991
    OR SMALLER THAN -9007199254740991, 
    DISPLAY "ERROR - TOO LARGE"
    AND CLEAR EVERYTHING

*/